### ISSUE TITLE
Stop gulp.watch on Sass error

### ISSUE THREAD

**Issue by Cybercraft** [Squiweb/headstart#1]
Afin déviter que gulp.watch ne s'arréte sur une erreur
### In Gulp.task 'sass'
```javascript
.pipe $.sass().on('error', errorHandler)
```

### Create errorHandler function in the end of file
```javascript
errorHandler = (error) ->
    console.log error.toString()
    @emit 'end'
    return
```

**Comment by Squiweb** [comment]
Patched this issue using gulp plumber :+1:
